### ISSUE TITLE
Modifying the "simpler text"

### ISSUE THREAD

**Issue by Marxist-Leninist** [badboysm890/clara-copilot#1]
`vscode.window.showWarningMessage("Search with words that are simple !!")`
line 21 in extension.js it should be made clearer to the users what's happenings so something like
`vscode.window.showWarningMessage("Server returned no code - Search with words that are simple !!")`

**Comment by badboysm890** [comment]
Thanks for suggestions, will change it to vscode.window.showWarningMessage("Server returned no code - Search with words that are simple !!")
or you could just contribute too becoz im working on a interface that is similar to OG Copilot

**Comment by Marxist-Leninist** [comment]
Okay, I have done. Sort of new to GitHub (Though I have done programming for ages), but I did fork thing, presumably you can "pull??" it back into your master version

**Comment by Marxist-Leninist** [comment]
Yh, add me to Contribute
