### ISSUE TITLE
Server returned no code

### ISSUE THREAD

**Issue by tiagofrancafernandes** [badboysm890/clara-copilot#6]
Hi, I run it and get this error:

`Server returned no code - Search with words that are simple`

I used simple words.

I'd try in python 'python loops' like the sample but returned the same.

I am PHP programer. In PHP get the same.

![image](https://user-images.githubusercontent.com/8310974/127339385-04d6388a-740e-4c93-930b-b360000664a4.png)

**Comment by badboysm890** [comment]
No using python loop as a search string works probably network issue or firewall

**Comment by Dhananjay-JSR** [comment]
same issue
![image](https://user-images.githubusercontent.com/47073516/128635188-91790fd7-8f86-4fb1-8dc9-0413290179c2.png)

**Comment by Dhananjay-JSR** [comment]
> 
> 
> same issue
> ![image](https://user-images.githubusercontent.com/47073516/128635188-91790fd7-8f86-4fb1-8dc9-0413290179c2.png)

Looks like the https://www.codegrepper.com API you are using no longer exist

**Comment by badboysm890** [comment]
> 
> 
> > same issue
> > ![image](https://user-images.githubusercontent.com/47073516/128635188-91790fd7-8f86-4fb1-8dc9-0413290179c2.png)
> 
> Looks like the https://www.codegrepper.com API you are using no longer exist

No that's not an issue I have looked into it and it still work will create a fall back though 🤔

**Comment by Dhananjay-JSR** [comment]
so it worked for you ?? Strange
